DEFINE
	COLUMN '__SQDS0VisualCalcs'[Moving average] = 
		(/* USER DAX BEGIN */
BLANK()
/* USER DAX END */)

	COLUMN '__SQDS0VisualCalcs'[Moving average 1] = 
		(/* USER DAX BEGIN */
BLANK()
/* USER DAX END */)

	VAR __SQDS0FilterTable = 
		TREATAS({"All Segments"}, '_slicer Customer Segment - Executive Summary'[Segment])

	VAR __SQDS0FilterTable2 = 
		TREATAS(
			{"International",
				"UK",
				"Domestic (UK)"},
			'dim_geography'[Where are customers from]
		)

	VAR __SQDS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL(
				ROLLUPGROUP('dim_date'[Short Month], 'dim_date'[Month]), "IsSQDS0GrandTotalRowTotal"
			),
			__SQDS0FilterTable,
			__SQDS0FilterTable2,
			"v_slicer___Sales_YTD___2011_", '_Measures'[_slicer - Sales YTD (_2011)]
		)

	VAR __SQDS0VisualCalcsInput = 
		SELECTCOLUMNS(
			KEEPFILTERS(
				SELECTCOLUMNS(
					__SQDS0Core,
					"Short_Month", 'dim_date'[Short Month],
					"Month", 'dim_date'[Month],
					"IsSQDS0GrandTotalRowTotal", [IsSQDS0GrandTotalRowTotal],
					"v_slicer___Sales_YTD___2011_", [v_slicer___Sales_YTD___2011_]
				)
			),
			"Short Month", [Short_Month],
			"Month", [Month],
			"IsSQDS0GrandTotalRowTotal", [IsSQDS0GrandTotalRowTotal],
			"_slicer - Sales YTD (_2011)", [v_slicer___Sales_YTD___2011_]
		)

	TABLE '__SQDS0VisualCalcs' = 
		__SQDS0VisualCalcsInput
		WITH VISUAL SHAPE
			AXIS rows
				GROUP
					[Short Month],
					[Month]
					TOTAL [IsSQDS0GrandTotalRowTotal]
				ORDER BY
					[Month] ASC,
					[Short Month] ASC
			DENSIFY "IsDensifiedRow"

	VAR __SQDS0RemoveEmptyDensified = 
		FILTER(
			KEEPFILTERS('__SQDS0VisualCalcs'),
			OR(
				NOT('__SQDS0VisualCalcs'[IsDensifiedRow]),
				NOT(ISBLANK('__SQDS0VisualCalcs'[Moving average]))
			)
		)

	VAR __DS0Core = 
		SELECTCOLUMNS(
			KEEPFILTERS(
				FILTER(
					KEEPFILTERS(__SQDS0RemoveEmptyDensified),
					'__SQDS0VisualCalcs'[IsSQDS0GrandTotalRowTotal] = FALSE
				)
			),
			"'__SQDS0VisualCalcs'[Short Month]", '__SQDS0VisualCalcs'[Short Month],
			"'__SQDS0VisualCalcs'[Moving average]", '__SQDS0VisualCalcs'[Moving average],
			"'__SQDS0VisualCalcs'[Moving average 1]", '__SQDS0VisualCalcs'[Moving average 1],
			"'__SQDS0VisualCalcs'[_slicer - Sales YTD (_2011)]", '__SQDS0VisualCalcs'[_slicer - Sales YTD (_2011)],
			"'__SQDS0VisualCalcs'[Month]", '__SQDS0VisualCalcs'[Month]
		)

	VAR __DS0RemoveContextOnlyColumns = 
		SELECTCOLUMNS(
			KEEPFILTERS(__DS0Core),
			"'__SQDS0VisualCalcs'[Short Month]", '__SQDS0VisualCalcs'[Short Month],
			"'__SQDS0VisualCalcs'[_slicer - Sales YTD (_2011)]", '__SQDS0VisualCalcs'[_slicer - Sales YTD (_2011)],
			"'__SQDS0VisualCalcs'[Month]", '__SQDS0VisualCalcs'[Month]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			1001,
			__DS0RemoveContextOnlyColumns,
			'__SQDS0VisualCalcs'[Month],
			1,
			'__SQDS0VisualCalcs'[Short Month],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'__SQDS0VisualCalcs'[Month], '__SQDS0VisualCalcs'[Short Month]