table dim_product
	lineageTag: 4bc1db63-5cd1-4873-8d69-17694ebd65df

	column StockCode
		dataType: string
		lineageTag: 740be59d-0b80-4912-a712-22b81c525b46
		summarizeBy: none
		sourceColumn: StockCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 632912b7-c7aa-4aeb-8dce-a6b175c48503
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column AveragePrice
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 3de11bfb-5424-49e6-a4fb-7c50cee24ce7
		summarizeBy: sum
		sourceColumn: AveragePrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column TotalQuantitySold
		dataType: int64
		formatString: 0
		lineageTag: a92acd79-bced-4002-8d9d-05b1c623f14b
		summarizeBy: sum
		sourceColumn: TotalQuantitySold

		annotation SummarizationSetBy = Automatic

	column FirstSaleDate
		dataType: dateTime
		formatString: General Date
		lineageTag: c5ccc7e0-6b32-4174-8869-a387c8b13bae
		summarizeBy: none
		sourceColumn: FirstSaleDate

		variation Variation
			isDefault
			relationship: 691d2fdd-2dd5-4ec9-b5d4-20d557ccd123
			defaultHierarchy: LocalDateTable_6a8adc81-d213-4f31-93f3-e2185ec86848.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastSaleDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 6eac2a51-4a23-4df7-be7c-6721c2c7cb01
		summarizeBy: none
		sourceColumn: LastSaleDate

		variation Variation
			isDefault
			relationship: ea4da1bb-f29c-483d-ba86-40d5fa9728dc
			defaultHierarchy: LocalDateTable_43a6c7b9-db1e-45e7-9181-3e3b13380e94.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e7b0b118-c16e-4e82-84a7-1e8fb5983275
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d169dd76-8451-45c9-9863-0d7327642f88
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pzoladkiewicz\Documents\senior-bi-craftsman-journey\projects\Retail-Omnichannel-Optimization\data\processed\dim_product.csv"),[Delimiter=",", Columns=10, Encoding=1250, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StockCode", type text}, {"ProductName", type text}, {"AveragePrice", type text}, {"TotalQuantitySold", Int64.Type}, {"FirstSaleDate", type datetime}, {"LastSaleDate", type datetime}, {"ProductKey", Int64.Type}, {"IsGift", Int64.Type}, {"IsPostage", Int64.Type}, {"Category", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"AveragePrice", type number}}, "en-GB"),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type with Locale",{"IsGift", "IsPostage"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

