table 'dwh D_Date'
	lineageTag: 7dc17038-690e-44ad-9668-fcd7b17672fb
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 391d27db-90b7-415a-b272-f2d7b33be896
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 7ef17eef-b7cd-4276-a79f-ae8952993af4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: bcfdfb83-9ab1-4154-9c28-697c52652fe0
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 82754ff7-bfe1-4698-8da2-8bf1f263f3bb
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 60f5670a-f104-4007-8a07-a3309a7fe111
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 89440bee-b4c4-4489-9e75-92c9f98914da
		summarizeBy: none
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = User

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 7820f9b8-381a-4448-936d-0a2eabf45976
		summarizeBy: none
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = User

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 7c4b5d9c-2ee2-4195-a213-51bb33755e64
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = User

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: 230aafcb-1ace-4d88-9090-927483f48304
		summarizeBy: none
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = User

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 97f78905-14ca-4e43-8da0-5811c658ef8e
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 86d7a1af-241a-4b7d-b409-8ed26aab82a9
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: f308f0bc-b277-4ac4-986d-147d9e420a89
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = User

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: a80b8659-324a-4c8e-a0fb-200847504001
		summarizeBy: none
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = User

	column MonthShort = FORMAT('dwh D_Date'[Date], "MMM")
		lineageTag: 599041a1-6131-40b0-82b8-5bfb0c282b37
		summarizeBy: none
		sortByColumn: 'Month Name'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: c523824f-ee20-478f-b7e1-5aef9506e87e
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YearMonthSort = 'dwh D_Date'[Year] * 100 + 'dwh D_Date'[Month]
		formatString: 0
		lineageTag: 2690938e-28df-4cc8-a102-5c86ab0779cc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Name Short'
		dataType: string
		lineageTag: 2f6bb0e8-c844-4256-8b50-0acfa796200e
		summarizeBy: none
		sourceColumn: Month Name Short
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name Initials'
		dataType: string
		lineageTag: 3cef4032-3f09-4588-b18e-5132eed7221b
		summarizeBy: none
		sourceColumn: Month Name Initials

		annotation SummarizationSetBy = Automatic

	partition 'dwh D_Date' = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost:51433", "SupplyChainDB"),
				    dwh_D_Date = Source{[Schema="dwh",Item="D_Date"]}[Data],
				    #"Inserted Month Name" = Table.AddColumn(dwh_D_Date, "Month Name", each Date.MonthName([Date]), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Month Name", "Month Name Short", each Date.ToText([Date], "MMM")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Month Name Initials", each Text.Start( Date.ToText ([Date], "MMM"), 1))
				in
				    #"Added Custom1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

