table dim_geography
	lineageTag: 67304305-ce07-477c-b3a6-66d88d056323

	column GeographyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 20b9ad3b-8b88-4b56-9d89-216ae777ee4d
		summarizeBy: none
		sourceColumn: GeographyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d258b8e6-10ea-416b-93b1-ae2d034e0d3c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column IsUK
		dataType: int64
		formatString: 0
		lineageTag: 52f06333-e0c5-4035-b4f4-ae033c45854e
		summarizeBy: none
		sourceColumn: IsUK

		annotation SummarizationSetBy = Automatic

	column CountryOriginal
		dataType: string
		lineageTag: 25a0b184-5e0d-4a4a-b8b7-2db10d6e2071
		summarizeBy: none
		sourceColumn: CountryOriginal

		annotation SummarizationSetBy = Automatic

	partition dim_geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pzoladkiewicz\Documents\senior-bi-craftsman-journey\projects\retail-omnichannel-optimization\data\processed\dim_geography.csv"),[Delimiter=",", Columns=8, Encoding=1250, QuoteStyle=QuoteStyle.None]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column5", "Column6", "Column7", "Column8"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Columns", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"GeographyKey", Int64.Type}, {"IsUK", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

